"$schema" = "https://schema.tauri.app/config/2"
productName = "EuoraCraft Launcher"
version = "0.1.0"
identifier = "com.euoracraft.launcher"

[build]
frontendDist = "EuoraCraftLauncher-UI/dist"
devUrl = "http://localhost:5173"

[app]
withGlobalTauri = false

[app.security]

[[app.windows]]
title = "EuoraCraft Launcher"
width = 1000
height = 700
minWidth = 900
minHeight = 600
decorations = false
visible = true
