from __future__ import annotations

from collections.abc import Callable
from typing import Any

from ECL.api.bridge import guard_ipc_handler
from ECL.api.frontend import FrontendApi

COMMAND_NAMES = (
    "frontend_ready",
    "launcher_errors_pending",
    "launcher_errors_ack",
    "system_ping",
    "system_memory",
    "launcher_info",
    "info_card_get",
    "user_agreement_get",
    "user_agreement_save",
    "user_agreement_clear",
    "export_logs",
    "logs_get_history",
    "process_instances",
    "process_input",
    "process_stop",
    "debug_process_spawn",
    "debug_reset_launcher_data",
    "debug_clear_plugins",
    "debug_devtools_open",
    "settings_get",
    "settings_set",
    "frontend_log",
    "game_versions",
    "game_loader_versions",
    "game_scan",
    "game_java_scan",
    "game_install",
    "game_uninstall",
    "game_config_get",
    "game_config_set",
    "game_config_patch",
    "game_instances",
    "game_version_stats",
    "game_version_settings_get",
    "game_version_settings_set",
    "game_instance_profile_get",
    "game_instance_profile_patch",
    "game_instance_profile_reset",
    "game_instance_icon_set",
    "game_instance_pin_order_set",
    "game_instance_categories_get",
    "game_instance_categories_upsert",
    "game_instance_categories_delete",
    "game_instance_folder_open",
    "game_instance_clone",
    "game_instance_import",
    "game_instance_export",
    "game_instance_files_check",
    "game_instance_files_repair",
    "game_instance_delete_to_trash",
    "game_operation_get",
    "game_operation_cancel",
    "game_world_list",
    "game_world_detail",
    "game_world_patch",
    "game_world_copy",
    "game_world_import",
    "game_world_export",
    "game_world_icon_set",
    "game_world_delete_to_trash",
    "game_world_backup_list",
    "game_world_backup_create",
    "game_world_backup_restore",
    "game_world_backup_lock",
    "game_world_backup_delete_to_trash",
    "game_screenshot_list",
    "game_screenshot_thumbnail",
    "game_screenshot_copy",
    "game_screenshot_save_as",
    "game_screenshot_delete_to_trash",
    "game_screenshot_set_cover",
    "game_screenshot_set_background",
    "game_server_list",
    "game_server_upsert",
    "game_server_delete",
    "game_server_reorder",
    "game_server_status_refresh",
    "game_resource_list",
    "game_resource_install",
    "game_resource_toggle",
    "game_resource_delete_to_trash",
    "game_resource_manifest_export",
    "game_resource_search",
    "game_resource_identify",
    "game_resource_update_check",
    "game_resource_update",
    "game_launch",
    "game_launch_cancel",
    "game_instance_stop",
    "game_crash_analyze",
    "game_crash_output",
    "game_crash_export",
    "accounts_list",
    "accounts_current",
    "accounts_add_offline",
    "accounts_default_skins",
    "accounts_set_offline_skin",
    "accounts_add_authlib",
    "accounts_select_authlib_profile",
    "accounts_microsoft_login_config",
    "accounts_authlib_login_config",
    "accounts_start_microsoft_login",
    "accounts_poll_microsoft_login",
    "accounts_cancel_microsoft_login",
    "accounts_complete_microsoft_login",
    "accounts_switch",
    "accounts_remove",
    "accounts_refresh_profile",
    "accounts_set_favorite",
    "accounts_set_pinned",
    "accounts_texture_urls",
    "wardrobe_list",
    "wardrobe_import",
    "wardrobe_sync_account_skin",
    "wardrobe_update",
    "wardrobe_delete",
    "wardrobe_texture",
    "wardrobe_export",
    "wardrobe_apply_skin",
    "microsoft_reset_skin",
    "microsoft_set_cape",
    "microsoft_reset_cape",
    "authlib_resolve_server",
    "authlib_servers",
    "image_save_url",
    "image_fetch_data_url",
    "image_save_as",
    "image_read_file",
    "image_list_files",
    "select_directory",
    "select_java",
    "select_image",
    "select_file",
    "select_files",
    "select_save_file",
    "open_folder",
    "open_url",
    "file_resolve",
    "fs_exists",
    "fs_read_dir",
    "fs_read_file",
    "get_mods",
    "toggle_mod",
    "add_mod",
    "remove_mod",
    "open_mods_folder",
    "search_mods",
    "mod_source_config",
    "get_mod_info",
    "get_mod_versions",
    "download_mod",
    "plugin_list",
    "plugin_info",
    "plugin_enable",
    "plugin_disable",
    "plugin_unload",
    "plugin_reload",
    "plugin_install",
    "plugin_get_routes",
    "plugin_get_slots",
    "plugin_get_vue_slots",
    "plugin_get_vue_components",
    "plugin_call_command",
    "plugin_get_settings",
    "plugin_update_setting",
    "plugin_notify_sidebar_state",
    "connector_status",
    "connector_host_port",
    "connector_host_instance",
    "connector_join",
    "connector_leave",
    "connector_kick",
    "connector_match_instances",
    "connector_easytier_status",
    "connector_easytier_download",
    "connector_detect_ports",
    "connector_search_mc_port",
    "connector_nat_type",)


def command_handlers(api: FrontendApi) -> dict[str, Callable[..., Any]]:
    """
    返回 PyTauri 需要注册的唯一正式 IPC 命令表。

    :param api: 已连接应用上下文的前端 API 门面
    :return: 命令名到处理器的稳定映射
    """
    return {name: guard_ipc_handler(api, name, getattr(api, name)) for name in COMMAND_NAMES}


__all__ = ["COMMAND_NAMES", "command_handlers"]
