name: Ruff Lint

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  ruff:
    name: Run ruff
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-python
        with:
          python-version: '3.x'
          install-command: 'pip install ruff'

      - name: Run ruff
        run: |
          # Run ruff over the repository and output GitHub annotations
          ruff check . --format github
